import 'package:flutter/material.dart';
import '../widgets/math_markdown_renderer.dart';

class LatexExportService {
  static String convertToLatex(String markdownContent) {
    String latexContent = markdownContent;

    // Convert headers
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'^# (.+)$', multiLine: true),
      (match) => '\\section{${match.group(1)}}',
    );
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'^## (.+)$', multiLine: true),
      (match) => '\\subsection{${match.group(1)}}',
    );
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'^### (.+)$', multiLine: true),
      (match) => '\\subsubsection{${match.group(1)}}',
    );

    // Convert bold and italic
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\*\*(.+?)\*\*'),
      (match) => '\\textbf{${match.group(1)}}',
    );
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\*(.+?)\*'),
      (match) => '\\textit{${match.group(1)}}',
    );

    // Convert code blocks
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'```(\w+)?\n(.*?)\n```', dotAll: true),
      (match) {
        final language = match.group(1) ?? '';
        final code = match.group(2) ?? '';
        return '\\begin{verbatim}\n$code\n\\end{verbatim}';
      },
    );

    // Convert inline code
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'`(.+?)`'),
      (match) => '\\texttt{${match.group(1)}}',
    );

    // Convert lists
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'^- (.+)$', multiLine: true),
      (match) => '\\item ${match.group(1)}',
    );

    // Convert math blocks (already in LaTeX format)
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\$\$(.+?)\$\$', dotAll: true),
      (match) => '\\[\n${match.group(1)}\n\\]',
    );

    // Convert inline math (already in LaTeX format)
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\$(.+?)\$'),
      (match) => '\\(${match.group(1)}\\)',
    );

    // Convert tables (basic support)
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'^\|(.+)\|\$', multiLine: true),
      (match) {
        final row = match.group(1)!;
        final cells = row.split('|').map((cell) => cell.trim()).toList();
        final latexRow = cells.join(' & ');
        return '$latexRow \\\\';
      },
    );

    // Convert links
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\[([^\]]+)\]\(([^)]+)\)'),
      (match) => '\\href{${match.group(2)}}{${match.group(1)}}',
    );

    // Convert line breaks
    latexContent = latexContent.replaceAllMapped(
      RegExp(r'\n\n'),
      (match) => '\n\n',
    );

    return latexContent;
  }

  static String generateLatexDocument(String title, String content) {
    final convertedContent = convertToLatex(content);
    
    return '''
\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{geometry}
\\usepackage{listings}
\\usepackage{xcolor}
\\usepackage{verbatim}

\\geometry{a4paper, margin=1in}

\\title{$title}
\\author{Generated by Connected Notebook}
\\date{\\today}

\\begin{document}

\\maketitle

$convertedContent

\\end{document}
''';
  }

  static String generateBeamerPresentation(String title, String content) {
    final convertedContent = convertToLatex(content);
    
    return '''
\\documentclass[12pt]{beamer}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{listings}
\\usepackage{xcolor}

\\usetheme{Madrid}
\\usecolortheme{default}

\\title{$title}
\\author{Generated by Connected Notebook}
\\date{\\today}

\\begin{document}

\\frame{\\titlepage}

$convertedContent

\\end{document}
''';
  }

  static String generateLatexReport(String title, String author, String content) {
    final convertedContent = convertToLatex(content);
    
    return '''
\\documentclass[12pt,a4paper]{report}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{geometry}
\\usepackage{listings}
\\usepackage{xcolor}
\\usepackage{verbatim}
\\usepackage{fancyhdr}
\\usepackage{tocbibind}

\\geometry{a4paper, margin=1in}

\\title{$title}
\\author{$author}
\\date{\\today}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyhead[L]{\\leftmark}
\\fancyhead[R]{\\thepage}
\\fancyfoot[C]{\\thepage}

\\begin{document}

\\maketitle
\\tableofcontents
\\newpage

$convertedContent

\\end{document}
''';
  }
}
