// Mocks generated by Mockito 5.4.6 from annotations
// in connected_notebook/test/features/notes/providers/note_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connected_notebook/features/notes/models/note_model.dart'
    as _i4;
import 'package:connected_notebook/features/notes/repositories/note_repository.dart'
    as _i2;
import 'package:connected_notebook/features/notes/services/search_service_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i2.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Note>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<_i4.Note?> getNoteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i3.Future<_i4.Note?>.value(),
          )
          as _i3.Future<_i4.Note?>);

  @override
  _i3.Future<List<_i4.Note>> searchNotes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<int> addNote(_i4.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [note]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateNote(_i4.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNote(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Note>> getRecentNotes({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentNotes, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<List<_i4.Note>> getPendingTasks({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTasks, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<Map<String, dynamic>> getDatabaseStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabaseStats, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.Backlink>> getBacklinksForNote(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getBacklinksForNote, [noteId]),
            returnValue: _i3.Future<List<_i4.Backlink>>.value(<_i4.Backlink>[]),
          )
          as _i3.Future<List<_i4.Backlink>>);

  @override
  _i3.Future<List<_i4.Backlink>> getOutgoingLinksForNote(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getOutgoingLinksForNote, [noteId]),
            returnValue: _i3.Future<List<_i4.Backlink>>.value(<_i4.Backlink>[]),
          )
          as _i3.Future<List<_i4.Backlink>>);

  @override
  _i3.Future<void> updateBacklinks(_i4.Note? note, List<_i4.Note>? allNotes) =>
      (super.noSuchMethod(
            Invocation.method(#updateBacklinks, [note, allNotes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getFolders, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<int> getNoteCountInFolder(String? folderName) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteCountInFolder, [folderName]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Note>> getNotesByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByTag, [tag]),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<Map<String, int>> getTagFrequency() =>
      (super.noSuchMethod(
            Invocation.method(#getTagFrequency, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i5.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Note>> searchNotes(
    String? query, [
    List<_i4.Note>? allNotes,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query, allNotes]),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<List<_i4.Note>> getLinkedNotes(
    int? noteId,
    List<_i4.Note>? allNotes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedNotes, [noteId, allNotes]),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);

  @override
  _i3.Future<List<_i4.Note>> getReferringNotes(
    int? noteId,
    List<_i4.Note>? allNotes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReferringNotes, [noteId, allNotes]),
            returnValue: _i3.Future<List<_i4.Note>>.value(<_i4.Note>[]),
          )
          as _i3.Future<List<_i4.Note>>);
}
